"""Exports some useful Unicode constants"""

LDQM = "\N{LEFT DOUBLE QUOTATION MARK}"
RDQM = "\N{RIGHT DOUBLE QUOTATION MARK}"

NBSP = "\N{NO-BREAK SPACE}"
OCTO_NBSP = NBSP * 8
THSP = "\N{THIN SPACE}"
HAIRSP = "\N{HAIR SPACE}"
CGJ = "\N{COMBINING GRAPHEME JOINER}"
ZWJ = "\N{ZERO WIDTH JOINER}"
DOUB_VERT_LINE = "\N{DOUBLE VERTICAL LINE}"  # ‖
