""" Exports names for Unicode Hebrew points """

METEG = '\N{HEBREW POINT METEG}'
JSVARIKA = '\N{HEBREW POINT JUDEO-SPANISH VARIKA}'
DAGESH_OM = '\N{HEBREW POINT DAGESH OR MAPIQ}'
RAFE = '\N{HEBREW POINT RAFE}'
SHIND = '\N{HEBREW POINT SHIN DOT}'
SIND = '\N{HEBREW POINT SIN DOT}'
SHEVA = '\N{HEBREW POINT SHEVA}'
XSEGOL = '\N{HEBREW POINT HATAF SEGOL}'
XPATAX = '\N{HEBREW POINT HATAF PATAH}'
XQAMATS = '\N{HEBREW POINT HATAF QAMATS}'
XIRIQ = '\N{HEBREW POINT HIRIQ}'
TSERE = '\N{HEBREW POINT TSERE}'
SEGOL = '\N{HEBREW POINT SEGOL}'
PATAX = '\N{HEBREW POINT PATAH}'
QAMATS = '\N{HEBREW POINT QAMATS}'
QAMATS_Q = '\N{HEBREW POINT QAMATS QATAN}'
XOLAM_XFV = '\N{HEBREW POINT HOLAM HASER FOR VAV}'
XOLAM = '\N{HEBREW POINT HOLAM}'
QUBUTS = '\N{HEBREW POINT QUBUTS}'

DROP_VARIKA = str.maketrans({JSVARIKA: None})
