""" Exports some useful Unicode constants. """
NBSP = '\N{NO-BREAK SPACE}'
OCTO_NBSP = NBSP * 8
THSP = '\N{THIN SPACE}'
SOPA = '\N{HEBREW PUNCTUATION SOF PASUQ}'
MAQ = '\N{HEBREW PUNCTUATION MAQAF}'
PAS = '\N{HEBREW PUNCTUATION PASEQ}'
NUN_HAF = '\N{HEBREW PUNCTUATION NUN HAFUKHA}'
CGJ = '\N{COMBINING GRAPHEME JOINER}'
ZWJ = '\N{ZERO WIDTH JOINER}'
